name: PyInstaller CI

on: 
  push:
    branches: 
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'speed-test-monit.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'SpeedTest Monit'
          options: --onefile, --name "SpeedTest Monit", --console,
          is_uploaded: true

  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'speed-test-monit.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'SpeedTest Monit'
          options: --onefile, --name "SpeedTest Monit", --console,
          is_uploaded: true
